# Remove '#' to select a file or turn off linting.

# Linting with BLACK (Python) enhances code suggestions from LLMs. To disable linting, uncomment the relevant option in the linting settings.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[linting]
# "linting" = "off"

[files]
#"core/ai.py" = "selected"
#"core/file_manager.py" = "selected"
# "core/git_manager.py" = "selected"
# "core/tools.py" = "selected"
# "generate.py" = "selected"
#"pyproject.toml" = "selected"
# "test.py" = "selected"
# "tests/test_git_manager.py" = "selected"
# 