# Remove '#' to select a file or turn off linting.

# Linting with BLACK (Python) enhances code suggestions from LLMs. To disable linting, uncomment the relevant option in the linting settings.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[linting]
# "linting" = "off"

[files]
# "README.md" = "selected"
"core/ai.py" = "selected"
"core/file_manager.py" = "selected"
"core/file_memory.py" = "selected"
"core/file_selector.py" = "selected"
"core/git_manager.py" = "selected"
# "file_selection_example.toml" = "selected"
# "generate.py" = "selected"
# "poetry.lock" = "selected"
# "pyproject.toml" = "selected"
# "test.py" = "selected"
# "tests/test_git_manager.py" = "selected"
# 