name: Initialize File Memory

on:
  workflow_dispatch:  # Allow manual triggering
    inputs:
      force_run:
        description: 'Force execution even for automated commits'
  push:
    branches:
      - main

jobs:
  init-memory:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check if commit is from automation
        id: check_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          echo "is_bot_commit=$(echo $COMMIT_MSG | grep -q 'Update file memory [skip ci]' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install bella-issues-bot
        run: |
          python -m pip install --upgrade pip
          pip install bella-issues-bot

      - name: Initialize file memory
        if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.force_run == 'true') || (steps.check_commit.outputs.is_bot_commit == 'false') }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          GIT_REMOTE: ${{ github.server_url }}/${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          bella-file-memory -d . -m gpt-4o -t 0.7

      - name: Commit memory files if changed
        if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.force_run == 'true') || (steps.check_commit.outputs.is_bot_commit == 'false') }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .eng/memory/
          git diff --staged --quiet || git commit -m "Update file memory [skip ci]"
          git push
